name: Maven tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Run Cucumber via Maven (headless)
        env:
          CI: "true"
        run: |
          echo "Chrome version: $(google-chrome --version)"
          xvfb-run -a mvn -B ^
            "-Dtest=runner.RunCucumberTest" ^
            "-Dcucumber.features=src/test/resources/features/open.feature" ^
            "-Dcucumber.glue=stepdef" ^
            "-Dcucumber.plugin=pretty,summary,html:target/cucumber.html" ^
            "-Dbrowser=chrome" ^
            test

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            target/surefire-reports
            target/cucumber.html
            target/cucumber-reports/**
          if-no-files-found: ignore
